name: Unit Tests

on:
  pull_request:
    branches:
    - main
    - development
    - production
    types: [opened, synchronize]
  issue_comment:
    types: [created]
    body: /build
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '*-requirements.txt'

    - name: Upgrade Pip
      run: python -m pip install --upgrade pip

    - name: Install Requirements
      run: |
        pip3 install -r requirements.txt
        pip3 install -r dev-requirements.txt

    - name: Download Static
      run: |
        python3 toolbox/infra/cli/download_static.py

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s toolbox_test
      env:
        DEFAULT_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"